src/apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'users'

registration_patterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('password/change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

urlpatterns = [
    path('', include(registration_patterns)),
    path('account/delete', UserDeleteView.as_view(), name='delete'),
    path('account/image/change', UserImageUpdateView.as_view(), name='update_image'),
    path('account/address/edit', UserAddressUpdateView.as_view(), name='update_address'),
    path('account/edit', UserUpdateView.as_view(), name='update'),
    path('account/<username>', UserDetailView.as_view(), name='profile'),
    path('distributors/pending', DistributorPendingListView.as_view(), name='distributors'),
    path('account/<username>/approve', DistributorApproveView.as_view(), name='approve'),
    path('account/<username>/reject', DistributorRejectView.as_view(), name='reject'),
]

src/apps/address/urls.py
from django.urls import path

from .views import (
    AddressCreateView,
    AddressDeleteView,
    AddressUpdateView,
)

app_name = 'address'

urlpatterns = [
    path('create', AddressCreateView.as_view(), name='create'),
    path('update/<pk>', AddressUpdateView.as_view(), name='update'),
    path('delete', AddressDeleteView.as_view(), name='delete'),
]

src/apps/cart/urls.py
from django.urls import path
from .views import *

app_name = 'carts'

urlpatterns = [
    path('', CartView.as_view(), name='detail'),
    path('update/quantity', CartItemUpdateQuantityView.as_view(), name='update_qty'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('checkout/done', CheckoutDoneView.as_view(), name='checkout_done'),
]

src/apps/product/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('distributor/<username>', ProductDistributorListView.as_view(), name='distributor'),
    path('category/<slug>', ProductCategoryListView.as_view(), name='category'),
    path('delete/request', ProductDeleteRequest.as_view(), name="delete_request"),
    path('delete/pending', ProductDeletePendingListView.as_view(), name='delete_pending'),
    path('approve/pending', ProductApprovePendingListView.as_view(), name='approve_pending'),
    path('create', ProductCreateView.as_view(), name="create"),
    path('search', ProductFilterView.as_view(), name='search'),
    path('featured', ProductFeaturedView.as_view(), name='featured'),
    path('<slug>', ProductDetailView.as_view(), name='detail'),
    path('<slug>/add', ProductAddToCartView.as_view(), name='add_to_cart'),
    path('<slug>/remove', ProductRemoveFromCartView.as_view(), name='remove_from_cart'),
    path('<slug>/rate', ProductRateView.as_view(), name='rate'),
    path('<slug>/edit', ProductUpdateView.as_view(), name='update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name="delete"),
    path('<slug>/approve/', ProductApproveView.as_view(), name='approve'),
    path('<slug>/reject/', ProductRejectView.as_view(), name='reject'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('products/', include('product.urls')),
    path('address/', include('address.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from decimal import Decimal

User = get_user_model()


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(_('Quantity'), default=0)
    item_total = models.DecimalField(_('Total Price'), default=0.00, max_digits=100, decimal_places=2)
    is_active = models.BooleanField(_('Active'), default=True)

    class Meta:
        verbose_name = _('Cart Item')
        verbose_name_plural = _('Cart Items')
        unique_together = ['cart', 'product']

    def __str__(self):
        return self.product.__str__()

    def update_item_total_price(self):
        qts = self.quantity
        price = self.product.get_price()
        total = Decimal(qts) * price

        active = self.product.is_active
        approved = self.product.is_approved
        stock = self.product.stock
        self.is_active = active
        if active and approved and stock > 0:
            self.item_total = total
        else:
            self.item_total = 0


class Cart(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name='shopping_cart')

    products = models.ManyToManyField('product.Product',
                                      through='CartItem')

    total = models.DecimalField(_('Total'),
                                default=0.00,
                                max_digits=100,
                                decimal_places=2)

    subtotal = models.DecimalField(_('Subtotal'),
                                   default=0.00,
                                   max_digits=100,
                                   decimal_places=2)

    timestamp = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Cart')
        verbose_name_plural = _('Carts')

    def __str__(self):
        return self.user.username

    def get_total_tax(self):
        return self.total - self.subtotal

    def get_total_discount(self):
        discount = 0
        for p in self.products.all():
            discount += (p.price - p.discount_price)
        return Decimal(discount)

    def update_total_with_tax(self):
        if self.subtotal > 0:
            self.total = Decimal(self.subtotal) * Decimal(1.08)
        else:
            self.total = 0.00

    def get_total_with_discount(self):
        discount = self.get_total_discount()
        return self.total - discount

    def update_subtotal(self):
        total = 0
        cart_items = self.cartitem_set.all()
        for item in cart_items:
            total += item.item_total

        if self.subtotal != total:
            self.subtotal = total
            self.save()

src/apps/cart/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.utils.translation import gettext_lazy as _
from django.contrib import messages

from .models import CartItem
from order.models import Order
import random


class CartView(LoginRequiredMixin, View):

    def get(self, request):
        if request.user.is_staff or not request.user.type == 'customer':
            raise Http404
        instance = self.request.user.shopping_cart
        return render(request, 'shopping_cart.html', {'cart': instance})


class CartItemUpdateQuantityView(LoginRequiredMixin, View):

    def post(self, request):
        pk = request.POST.get('pk', None)
        qty = request.POST.get('qty', None)
        if pk and qty:
            item_qs = CartItem.objects.filter(pk=pk)
            if item_qs.exists():
                item = item_qs.first()
                item.quantity = qty
                item.save()
        return JsonResponse({})


class CheckoutView(LoginRequiredMixin, View):

    def get(self, request):
        if request.user.is_staff or not request.user.type == 'customer':
            raise Http404

        cart = request.user.shopping_cart
        addresses = request.user.addresses.all()
        shipping = request.user.shipping
        billing = request.user.billing
        context = {
            'cart': cart,
            'addresses': addresses,
            'shipping': shipping,
            'billing': billing,
        }
        return render(request, 'checkout.html', context)


class CheckoutDoneView(LoginRequiredMixin, View):

    def post(self, request):
        if request.user.is_staff or not request.user.type == 'customer':
            raise Http404

        user = request.user
        billing = user.billing
        shipping = user.shipping

        number = random.randint(1, 10)
        if number <= 3:
            info_message = _('An error occupied while trying to set order. Please try again.')
            messages.add_message(request, messages.INFO, info_message)
            return redirect('carts:checkout')

        if billing is not None and shipping is not None:
            cart = user.shopping_cart
            cart_items = cart.cartitem_set.all()
            order = Order.objects.create(
                user=user,
                billing_address=billing,
                shipping_address=shipping,
                total=cart.total
            )

            for item in cart_items:
                product = item.product
                if item.quantity > product.stock:
                    item.quantity = product.stock
                    item.save()

                product.stock -= item.quantity
                product.order_amount += item.quantity
                product.save()
                order.cart_items.add(item)

            order.save()
            for product in cart.products.all():
                items = CartItem.objects.all().filter(product=product, cart=cart)
                for item in items:
                    item.cart = None
                    item.save()

            info_message = _('Your order is placed.')
            messages.add_message(request, messages.INFO, info_message)
            return redirect('orders:list')

        info_message = _('You need to set a default billing and shipping addresses.')
        messages.add_message(request, messages.INFO, info_message)
        return redirect('carts:checkout')

src/apps/cart/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ request.user.username }} | {% trans "Checkout" %}{% endblock title %}
{% block content %}
    <section class="section-content bg padding-y border-top">
        <div class="container">
            <div class="row">
                {% if cart.products.count > 0 %}
                    <main class="col-md-8 mb-4">
                        <div class="card">
                            <table class="table shopping-cart-wrap">
                                <thead class="text-muted">
                                <tr>
                                    <th scope="col" width="10%">{% trans "Product" %}</th>
                                    <th scope="col" width="53%">{% trans "" %}</th>
                                    <th scope="col" width="12%">{% trans "Quantity" %}</th>
                                    <th scope="col" width="15%">{% trans "Price" %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for product in cart.products.all.active.not_deleted %}
                                    <tr>
                                        <td>
                                            <figure class="media">
                                                <div class="img-wrap">
                                                    <img src="{{ product.get_first_image_url }}"
                                                         alt="{{ product.name }}"
                                                         class="img-thumbnail img-sm">
                                                </div>
                                            </figure>
                                        </td>
                                        <td>
                                            <h6 class="title">
                                                {{ product.name }}
                                            </h6>
                                        </td>
                                        <td>
                                            {% for cart_item in cart.cartitem_set.all %}
                                                {% if product == cart_item.product %}
                                                    <p class="mt-2">{{ cart_item.quantity }}</p>
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                        <td>
                                            <div class="price-wrap mt-2">
                                                <var class="price text-dark">
                                                    {% for cart_item in cart.cartitem_set.all %}
                                                        {% if product.pk == cart_item.product.pk %}
                                                            ${{ cart_item.item_total }}
                                                        {% endif %}
                                                    {% endfor %}
                                                </var>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div> <!-- card.// -->
                    </main> <!-- col.// -->

                    <aside class="col-md-4">
                        <dl class="dlist-align">
                            <dt>{% trans "Subtotal" %}:</dt>
                            <dd class="text-right">${{ cart.subtotal }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>{% trans "Discount" %}:</dt>
                            <dd class="text-right">-${{ cart.get_total_discount }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>{% trans "Taxes" %}:</dt>
                            <dd class="text-right">${{ cart.get_total_tax }}</dd>
                        </dl>
                        <dl class="dlist-align h4">
                            <dt>{% trans "Total" %}:</dt>
                            <dd class="text-right"><strong>${{ cart.get_total_with_discount }}</strong></dd>
                        </dl>
                        <hr>
                        {% if billing or shipping %}
                            <div class="row">
                                {% if billing %}
                                    <div class="col-lg-6 mb-2">
                                        <div class="card">
                                            <div class="card-body">
                                                <figcaption class="info-wrap">
                                                    <h5 class="title">{% trans "Billing to" %}</h5>
                                                    <p class="text-muted">{{ billing.get_country_display }}</p>
                                                    <p class="text-muted">{{ billing.get_address }}</p>
                                                    <p class="text-muted">{{ billing.notes }}</p>
                                                </figcaption>
                                            </div>
                                        </div> <!-- card // -->
                                    </div> <!-- col // -->
                                {% endif %}
                                {% if shipping %}
                                    <div class="col-lg-6">
                                        <div class="card">
                                            <div class="card-body">
                                                <figcaption class="info-wrap">
                                                    <h5 class="title">{% trans "Shipping to" %}</h5>
                                                    <p class="text-muted">{{ shipping.get_country_display }}</p>
                                                    <p class="text-muted">{{ shipping.get_address }}</p>
                                                    <p class="text-muted">{{ shipping.notes }}</p>
                                                </figcaption>
                                            </div>
                                        </div> <!-- card // -->
                                    </div> <!-- col // -->
                                {% endif %}
                            </div> <!-- row.// -->
                            <div class="row mb-2 mt-2">
                                <div class="col text-right">
                                    <a href="{{ request.user.get_absolute_url }}">{% trans "Change Current Address" %}</a>
                                </div>
                            </div>
                        {% endif %}
                        {% if not billing or not shipping %}
                            {% if addresses.count > 0 %}
                                <div class="row mb-2">
                                    {% for address in addresses %}
                                        <div class="col">
                                            <article class="box h-100">
                                                <figure class="itembox text-center">
                                                    <span class="mt-2 icon-wrap rounded icon-sm bg-dark"><i
                                                            class="fas fa-truck white"></i></span>
                                                    <figcaption class="text-wrap">
                                                        <h5 class="title">{{ address.get_country_display }}</h5>
                                                        <p class="text-muted">{{ address.get_address }}</p>
                                                        <p class="text-muted">{{ address.notes }}</p>
                                                    </figcaption>
                                                </figure> <!-- iconbox // -->
                                                <form action="{% url 'users:update_address' %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="address_pk" value="{{ address.pk }}">
                                                    {% if not request.user.shipping %}
                                                        <button type="submit" name="shipping"
                                                                class="btn btn-dark btn-block">
                                                            {% trans "Set as shipping" %}
                                                        </button>
                                                    {% endif %}
                                                    {% if not request.user.billing %}
                                                        <button type="submit" name="billing"
                                                                class="btn btn-dark btn-block">
                                                            {% trans "Set as billing" %}
                                                        </button>
                                                    {% endif %}
                                                </form>
                                            </article> <!-- panel-lg.// -->
                                        </div><!-- col // -->
                                    {% endfor %}
                                </div>
                            {% else %}
                                <div class="row">
                                    <div class="col">
                                        <a href="{% url 'address:create' %}">
                                            <span>{% trans "New Address" %}</span>
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                        {% endif %}
                        <dl class="ml-3 mt-1 float-right">
                            <dd class="text-right">
                                <form class="form-horizontal" action="{% url 'carts:checkout_done' %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-success" type="submit">
                                        {% trans "DONE" %}
                                    </button>
                                </form>
                            </dd>
                        </dl>
                        <dl class="float-right mt-1">
                            <dd>
                                <a role="button" href="{% url 'carts:detail' %}" class="btn btn-warning">
                                    {% trans "BACK" %}
                                </a>
                            </dd>
                        </dl>
                        <figure class="itemside mt-4 mb-3">
                            <aside class="aside"><img src="{% static 'uikit/images/icons/pay-visa.png' %}"></aside>
                            <div class="text-wrap small text-muted">
                                Pay 84.78 AED ( Save 14.97 AED )
                            </div>
                        </figure>
                        <figure class="itemside mb-3">
                            <aside class="aside"><img src="{% static 'uikit/images/icons/pay-mastercard.png' %}">
                            </aside>
                            <div class="text-wrap small text-muted">
                                Pay by MasterCard and Save 40%.
                            </div>
                        </figure>
                    </aside> <!-- col.// -->
                {% else %}
                    <main class="col-sm-12">
                        <h5 class="text-center">
                            {% trans "There are currently no products in your basket." %}
                        </h5>
                        <div class="text-center mt-3">
                            <a class="btn btn-lg btn-warning" role="button" aria-pressed="true"
                               href="{% url 'home' %}">
                                <i class="fas fa-shopping-basket"></i>
                                {% trans "Start shopping" %}
                            </a>
                        </div>
                    </main>
                {% endif %}
            </div>
        </div> <!-- container .//  -->
    </section>
{% endblock content %}


{% block script %}
    <script type="text/javascript">
        $(':input').on('keyup change click', function () {
            let value = parseInt($(this).val());
            if (value) {
                if (value < 0 || $(this).val().startsWith(0)) {
                    $(this).val(0);
                }

                let max = parseInt($(this).attr("max"));
                if (value > max) {
                    $(this).val(max);
                }
            }
        });
    </script>
{% endblock script %}