src/apps/account/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'users'

registration_patterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', UserRegisterView.as_view(), name='register'),
    path('password/change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password/reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm')
]

urlpatterns = [
    path('', include(registration_patterns)),
    path('account/delete', UserDeleteView.as_view(), name='delete'),
    path('account/image/change', UserImageUpdateView.as_view(), name='update_image'),
    path('account/address/edit', UserAddressUpdateView.as_view(), name='update_address'),
    path('account/edit', UserUpdateView.as_view(), name='update'),
    path('account/<username>', UserDetailView.as_view(), name='profile'),
    path('distributors/pending', DistributorPendingListView.as_view(), name='distributors'),
    path('account/<username>/approve', DistributorApproveView.as_view(), name='approve'),
    path('account/<username>/reject', DistributorRejectView.as_view(), name='reject'),
]

src/apps/cart/urls.py
from django.urls import path
from .views import *

app_name = 'carts'

urlpatterns = [
    path('', CartView.as_view(), name='detail'),
    path('update/quantity', CartItemUpdateQuantityView.as_view(), name='update_qty'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('checkout/done', CheckoutDoneView.as_view(), name='checkout_done'),
]

src/apps/order/urls.py
from django.urls import path, include

from .views import *

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='list'),
    path('detail/<order_id>', OrderDetailView.as_view(), name='detail'),
]

src/apps/product/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('distributor/<username>', ProductDistributorListView.as_view(), name='distributor'),
    path('category/<slug>', ProductCategoryListView.as_view(), name='category'),
    path('delete/request', ProductDeleteRequest.as_view(), name="delete_request"),
    path('delete/pending', ProductDeletePendingListView.as_view(), name='delete_pending'),
    path('approve/pending', ProductApprovePendingListView.as_view(), name='approve_pending'),
    path('create', ProductCreateView.as_view(), name="create"),
    path('search', ProductFilterView.as_view(), name='search'),
    path('featured', ProductFeaturedView.as_view(), name='featured'),
    path('<slug>', ProductDetailView.as_view(), name='detail'),
    path('<slug>/add', ProductAddToCartView.as_view(), name='add_to_cart'),
    path('<slug>/remove', ProductRemoveFromCartView.as_view(), name='remove_from_cart'),
    path('<slug>/rate', ProductRateView.as_view(), name='rate'),
    path('<slug>/edit', ProductUpdateView.as_view(), name='update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name="delete"),
    path('<slug>/approve/', ProductApproveView.as_view(), name='approve'),
    path('<slug>/reject/', ProductRejectView.as_view(), name='reject'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('products/', include('product.urls')),
    path('address/', include('address.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/templates/include/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'ecommerce/css/style.css' %}">

<link href="{% static 'uikit/css/bootstrap-custom.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'uikit/fonts/fontawesome/css/fontawesome-all.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'uikit/plugins/fancybox/fancybox.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'uikit/css/uikit.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'uikit/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

src/apps/templates/include/js.html
{% load static %}
<!-- Bootstrap Scripts -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"   integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="   crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'ecommerce/js/custom.js' %}"></script>

<!-- <script src="{% static 'uikit/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script> -->
<script src="{% static 'uikit/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script src="{% static 'uikit/plugins/fancybox/fancybox.min.js' %}" type="text/javascript"></script>
<script src="{% static 'uikit/js/script.js' %}" type="text/javascript"></script>

src/apps/templates/include/nav.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-parent navbar-expand-sm fixed-top">
  <div class="container">
    <div class="brand-wrap d-none d-sm-block">
      <a class="logo" href="{% url 'home' %}">
        <img src="{% static 'uikit/images/brand.png' %}" alt="Logo" width="50" height="50">
      </a>
    </div>

    {% if request.user.is_authenticated %}
      <li class="nav-link dropdown ml-auto">
        <button class="btn btn-outline-secondary" id="profileDropdown"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            style="padding: 8px 10px 8px 10px;">
          <span class="float-left mr-2 mt-1">
            <i class="fas fa-user fa-lg"></i>
          </span>
          <h6 class="float-left mt-1 d-none d-sm-block">{{ request.user.username }}</h6>
          <span class="float-right ml-2 mt-1">
            <i class="fas fa-angle-down fa-lg"></i>
          </span>
        </button>
        <div class="dropdown-menu mt-1" aria-labelledby="profileDropdown">
          <a class="dropdown-item" href="{{ request.user.get_absolute_url }}">{% trans "Profile" %}</a>
          {% if request.user.type == 'customer' and not request.user.is_staff %}
          <a class="dropdown-item" href="{% url 'orders:list' %}">{% trans "Previous Orders" %}</a>
          {% endif %}
          <a class="dropdown-item" href="{{ request.user.get_absolute_url }}">{% trans "Settings" %}</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'users:logout' %}">{% trans "Sign out" %}</a>
        </div>
      </li>

      {% if request.user.type == 'customer' and not request.user.is_staff %}
        <a href="{% url 'carts:detail' %}" role="button" aria-pressed="true"
          class="btn btn-secondary d-none d-sm-block bg-secondary" id="userBasket"
          style="padding: 8px 0 8px 10px;">
          <span class="float-left mr-3 mt-1">
            <i class="fas fa-shopping-cart fa-lg"></i>
          </span>
          <h6 class="float-left mt-1">{% trans "My Basket" %}</h6>
          <span class="badge badge-pill badge-danger"
              style="right: 90px; top: -8px;">
            {{ request.user.shopping_cart.cartitem_set.all.count }}
          </span>
        </a>
      {% else %}
      <a href="{% url 'products:create' %}" role="button" aria-pressed="true"
        class="btn btn-outline-info"
        style="padding: 8px 10px 8px 10px;">
        <span class="mt-1 mr-1 ml-1 d-sm-none d-block">
          <i class="fas fa-registered fa-lg"></i>
        </span>
        <h6 class="mt-1 d-none d-sm-block">{% trans "Register Product" %}</h6>
      </a>
      {% endif %}
    {% else %}
      <div class="col-lg-6-24 col-sm-7 col-8 order-2 order-lg-3">
        <div class="d-flex justify-content-end">
            <div class="widget-header">
                <small class="title text-muted">{% trans "Welcome guest!" %}</small>
                <div>
                    <a href="{% url 'users:login' %}">{% trans "Login" %}</a>
                    <span class="dark-transp"> | </span>
                    <a href="{% url 'users:register' %}"> {% trans "Register" %}</a>
                </div>
            </div>
        </div>
      </div>
    {% endif %}
  </div>
</nav>
<section class="navbar navbar-expand-sm navbar-child bg-danger">
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="text-white"><i class="fas fa-angle-down"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mx-auto my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">{% trans "HOME" %} <span class="sr-only">(current)</span></a>
      </li>
        {% if request.user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:approve_pending' %}">{% trans "REGISTERED PRODUCTS" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:distributors' %}">{% trans "REGISTERED DISTRIBUTORS" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:delete_pending' %}">{% trans "DELETED PRODUCTS" %}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:featured' %}">{% trans "FEATURED" %}</a>
            </li>
        {% endif %}
    </ul>
  </div>
</section>