src/apps/product/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('distributor/<username>', ProductDistributorListView.as_view(), name='distributor'),
    path('category/<slug>', ProductCategoryListView.as_view(), name='category'),
    path('delete/request', ProductDeleteRequest.as_view(), name="delete_request"),
    path('delete/pending', ProductDeletePendingListView.as_view(), name='delete_pending'),
    path('approve/pending', ProductApprovePendingListView.as_view(), name='approve_pending'),
    path('create', ProductCreateView.as_view(), name="create"),
    path('search', ProductFilterView.as_view(), name='search'),
    path('featured', ProductFeaturedView.as_view(), name='featured'),
    path('<slug>', ProductDetailView.as_view(), name='detail'),
    path('<slug>/add', ProductAddToCartView.as_view(), name='add_to_cart'),
    path('<slug>/remove', ProductRemoveFromCartView.as_view(), name='remove_from_cart'),
    path('<slug>/rate', ProductRateView.as_view(), name='rate'),
    path('<slug>/edit', ProductUpdateView.as_view(), name='update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name="delete"),
    path('<slug>/approve/', ProductApproveView.as_view(), name='approve'),
    path('<slug>/reject/', ProductRejectView.as_view(), name='reject'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('products/', include('product.urls')),
    path('address/', include('address.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/product/models.py
from django.db import models
import datetime
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils import timezone
from utils.utils import get_upload_path
from cart.models import CartItem
from decimal import Decimal
from django.db.models import Count, Q
from django.conf import settings

User = get_user_model()


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def not_active(self):
        return self.filter(is_active=False)

    def deleted(self):
        return self.filter(is_deleted=True).filter(is_active=True)

    def not_deleted(self):
        return self.filter(is_deleted=False)

    def approved(self):
        return self.filter(is_approved=True)

    def not_approved(self):
        return self.filter(is_approved=False)

    def accepted(self):
        return self.active().not_deleted().approved()

    def pending(self):
        return self.active().not_deleted().not_approved()

    def featured(self):
        qs_orders = self.accepted().by_order_amount(100)
        qs_likes = self.accepted().by_likes(10)
        qs_discounts = self.accepted().filter(discount__gte=20)
        return (qs_orders | qs_likes | qs_discounts).distinct()

    def by_order_amount(self, amount, category=None):
        if category is None:
            return self.accepted()\
                .annotate(order=Count('order_amount'))\
                .filter(order__gt=amount)
        return self.accepted()\
            .filter(category__name=category.name)\
            .annotate(order=Count('order_amount'))\
            .filter(order__gt=amount)

    def by_likes(self, like_amount):
        return self.accepted()\
            .annotate(num_like=Count('likes'))\
            .filter(num_like__gte=like_amount)

    def recent(self):
        return self.accepted().order_by("-updated", "-timestamp")

    def by_range(self, start_date, end_date=None):
        if end_date is None:
            return self.filter(updated__gte=start_date)
        return self.filter(updated__gte=start_date).filter(updated__lte=end_date)


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)


class Product(models.Model):
    distributor = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    category = models.ManyToManyField('category.Category', blank=True)
    name = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    description = models.TextField(_('Description'), default='')
    price = models.DecimalField(_('Price'), default=0.00, max_digits=100, decimal_places=2)
    discount_price = models.DecimalField(_('Discount Price'), default=0.00, max_digits=100, decimal_places=2)
    order_amount = models.PositiveIntegerField(_('Total order'), default=0)
    likes = models.ManyToManyField(User, through='ProductLike', related_name='likes')
    stock = models.PositiveIntegerField(_('Stock'), default=0)
    discount = models.PositiveIntegerField(_('Discount'), default=0)

    is_approved = models.BooleanField(default=False, verbose_name='Approved')
    is_deleted = models.BooleanField(default=False, verbose_name='Deleted')
    is_active = models.BooleanField(default=True, verbose_name='Active')

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

    def get_price(self):
        return Decimal(self.price)

    def get_absolute_price(self):
        if self.discount > 0:
            return Decimal(self.discount_price)
        return Decimal(self.price)

    def get_saved_price(self):
        if self.discount > 0:
            return Decimal(self.price) - Decimal(self.discount_price)

    def get_first_image_url(self):
        url = settings.STATIC_URL + 'ecommerce/img/defaults/no_image.jpg'
        if self.product_image.exists():
            url = self.product_image.first().image.url
        return url

    def is_todays_product(self):
        start_date = timezone.now().date() - datetime.timedelta(hours=24)
        qs_exist = Product.objects.all().filter(pk=self.pk).by_range(start_date).exists()
        return qs_exist

    def get_avg_like(self):
        like_count = self.likes.all().count()
        if like_count > 0:
            rate = 0
            for product in self.product_like.all():
                rate += product.rate
            avg = Decimal(rate / like_count)
            return avg
        return 0

    def update_cart_item(self):
        items = CartItem.objects.all().filter(product=self)
        for item in items:
            item.save()

    def update_discount_price(self):
        if self.discount > 0:
            total_price = self.get_price()
            discount_amount = total_price * Decimal(self.discount) / 100
            new_price = total_price - discount_amount
            self.discount_price = new_price
        else:
            self.discount_price = self.price


class ProductImage(models.Model):
    product = models.ForeignKey('Product',
                                on_delete=models.CASCADE,
                                related_name='product_image')

    image = models.ImageField(upload_to=get_upload_path,
                              height_field='height_field',
                              width_field='width_field',
                              null=True,
                              blank=True,
                              verbose_name='Product Image',
                              max_length=255)

    width_field = models.PositiveIntegerField(default=0,
                                              verbose_name='Image Width',
                                              null=True,
                                              blank=True)

    height_field = models.PositiveIntegerField(default=0,
                                               verbose_name='Image Height',
                                               null=True,
                                               blank=True)

    class Meta:
        verbose_name = _('Product Image')
        verbose_name_plural = _('Product Images')


class ProductLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('Product',
                                on_delete=models.SET_NULL,
                                null=True,
                                blank=True,
                                related_name='product_like')

    rate = models.DecimalField(default=0, max_digits=3, decimal_places=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Product Like')
        verbose_name_plural = _('Product Likes')
        unique_together = ['user', 'product']

    def _str_(self):
        return "{user} - {product}".format(user=self.user.username, product=self.product.name)

src/apps/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'ecommerce/img/favicon.png' %}">
  {% include "include/css.html" %}
  <style media="screen">{% block style %}{% endblock style %}</style>
</head>
<body>
  <header class="section-header">
    {% include "include/nav.html" %}
    {% block header %}{% endblock header %}
  </header>

  {% block content %}{% endblock content %}

  {% if messages %}
  {% for message in messages %}
    <div id="snackbar" style="z-index:999;">
      {{ message }}
      <button type="button" id="snackbarClose" class="close ml-2 my-auto">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
  {% endif %}

  {% include "include/js.html" %}
  <script type="text/javascript">
    $(document).ready(function() {
      showSnackbar();
    });

    function showSnackbar() {
      var snackbar = document.getElementById("snackbar");
      if (snackbar) {
        snackbar.className = "show";
        setTimeout(function () {
          snackbar.className = snackbar.className.replace("show", "");
        }, 6500);
      }
    }

    $('#snackbarClose').click(function() {
      $('#snackbar').hide();
    })
  </script>
  {% block script %}{% endblock script %}
</body>
</html>

src/apps/templates/home.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock title %}
{% block header %}
<section class="section-intro bg-danger text-white text-center">
    <div class="container d-flex flex-column" style="min-height:20vh;">
        <div class="row mt-auto">
            <div class="col-lg-9 col-md-8 col-sm-12 mx-auto text-center">
                <form class="form-noborder" method="GET" action="{% url 'products:search' %}">
                    <div class="form-row mb-5 my-4">
                        <div class="col-lg-10 col-sm-12 form-group">
                            <input class="form-control form-control-lg" name="q" placeholder="{% trans 'Search...' %}" type="text">
                        </div>
                        {% comment %}<div class="col-lg-3 col-sm-12 form-group">
                            <select class="custom-select form-control-lg" name="category">
                                <option value="all" selected>{% trans "Choose a category" %}</option>
                                {% for category in categories %}
                                    <option value="{{ category.slug }}"> {{ category.name }} </option>
                                {% endfor %}
                            </select>
                        </div>{% endcomment %}
                        <div class="col-lg-2 col-sm-12 form-group">
                            <button class="btn btn-warning btn-block btn-lg" type="submit">{% trans "Search" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock header %}

{% block content %}
<section class="section-content padding-y">
    <div class="container">
        {% if recent.count > 0 %}
            <div class="row">
                <div class="col">
                    <h5 class="title-text">
                        <span> Recent ({{ recent.count }})</span>
                    </h5>
                </div>
            </div>
        {% endif %}
        <div class="row">
            {% for p in recent %}
            {% if forloop.counter < 5 %}
                <div class="col-md-3">
                    <figure class="card card-product">
                        {% if p.is_todays_product %}
                            <span class="badge-new"> {% trans "NEW" %} </span>
                        {% endif %}
                        {% if p.stock == 0 %}
                            <span class="badge-new"> {% trans "NO STOCK" %} </span>
                        {% endif %}
                        {% if p.discount > 0 %}
                            <span class="badge-offer"><b>{{ p.discount }}%</b></span>
                        {% endif %}
                        <div class="img-wrap">
                            <img src="{{ p.get_first_image_url }}" alt="{{ p.name }}">
                        </div>
                        <figcaption class="info-wrap">
                            <a href="{{ p.get_absolute_url }}" class="title">{{ p.name }}</a>
                            <div class="action-wrap">
                                <div class="row">
                                    <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                        <div class="price-wrap h5">
                                            {% if p.discount > 0 %}
                                                <del class="price-old">${{p.price}}</del>
                                            {% endif %}
                                            <span class="price-new">${{p.discount_price}}</span>
                                        </div> <!-- price-wrap.// -->
                                    </div>
                                  {% if request.user.type == 'customer' and not request.user.is_staff and p.stock > 0 %}
                                  <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                    <form method="POST" action="{% url 'products:add_to_cart' p.slug %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="quantity" value="1">
                                        <input type="hidden" name="id" value="{{ p.pk }}">
                                        <button class="btn btn-outline-danger float-right" type="submit">
                                            {% trans "Add to cart" %}
                                        </button>
                                    </form>
                                  </div>
                                  {% endif %}
                                </div>
                            </div> <!-- action-wrap -->
                        </figcaption>
                    </figure> <!-- card // -->
                </div> <!-- col // -->
                {% endif %}
        {% endfor %}
        </div>
        {% if featured.count > 0 %}
            <div class="row">
                <div class="col">
                    <h5 class="title-text">
                        <span> Featured ({{ featured.count }})</span>
                        <a href="{% url 'products:featured' %}" class="float-right">
                            <span class="my-2" style="font-size:.8em">{% trans "Show all" %}</span>
                        </a>
                    </h5>
                </div>
            </div>
        {% endif %}
        <div class="row">
            {% for p in featured %}
            {% if forloop.counter < 5 %}
                <div class="col-md-3">
                    <figure class="card card-product">
                        {% if p.is_todays_product %}
                            <span class="badge-new"> {% trans "NEW" %} </span>
                        {% endif %}
                        {% if p.stock == 0 %}
                            <span class="badge-new"> {% trans "NO STOCK" %} </span>
                        {% endif %}
                        {% if p.discount > 0 %}
                            <span class="badge-offer"><b>{{ p.discount }}%</b></span>
                        {% endif %}
                        <div class="img-wrap">
                            <img src="{{ p.get_first_image_url }}" alt="{{ p.name }}">
                        </div>
                        <figcaption class="info-wrap">
                            <a href="{{ p.get_absolute_url }}" class="title">{{ p.name }}</a>
                            <div class="action-wrap">
                                <div class="row">
                                    <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                        <div class="price-wrap h5">
                                            {% if p.discount > 0 %}
                                                <del class="price-old">${{p.price}}</del>
                                            {% endif %}
                                            <span class="price-new">${{p.discount_price}}</span>
                                        </div> <!-- price-wrap.// -->
                                    </div>
                                  {% if request.user.type == 'customer' and not request.user.is_staff and p.stock > 0 %}
                                  <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                    <form method="POST" action="{% url 'products:add_to_cart' p.slug %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="quantity" value="1">
                                        <input type="hidden" name="id" value="{{ p.pk }}">
                                        <button class="btn btn-outline-danger float-right" type="submit">
                                            {% trans "Add to cart" %}
                                        </button>
                                    </form>
                                  </div>
                                  {% endif %}
                                </div>
                            </div> <!-- action-wrap -->
                        </figcaption>
                    </figure> <!-- card // -->
                </div> <!-- col // -->
                {% endif %}
        {% endfor %}
        </div>

        {% for category in categories  %}
            {% if category.product_set.all.accepted.count > 0 %}
                <div class="row">
                    <div class="col">
                        <h5 class="title-text">
                            <span> {{ category.name }} ({{ category.product_set.all.accepted.count }})</span>
                            <a href="{% url 'products:category' category.slug %}" class="float-right">
                                <span class="my-2" style="font-size:.8em">{% trans "Show all" %}</span>
                            </a>
                        </h5>
                    </div>
                </div>
            {% endif %}
            <div class="row">
                {% for p in category.product_set.all.accepted %}
                    {% if forloop.counter < 5 %}
                    <div class="col-md-3">
                        <figure class="card card-product">
                            {% if p.is_todays_product %}
                                <span class="badge-new"> {% trans "NEW" %} </span>
                            {% endif %}
                            {% if p.stock == 0 %}
                                <span class="badge-new"> {% trans "NO STOCK" %} </span>
                            {% endif %}
                            {% if p.discount > 0 %}
                                <span class="badge-offer"><b>{{ p.discount }}%</b></span>
                            {% endif %}
                            <div class="img-wrap">
                                <img src="{{ p.get_first_image_url }}" alt="{{ p.name }}">
                            </div>
                            <figcaption class="info-wrap">
                                <a href="{{ p.get_absolute_url }}" class="title">{{ p.name }}</a>
                                <div class="action-wrap">
                                    <div class="row">
                                        <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                            <div class="price-wrap h5">
                                                {% if p.discount > 0 %}
                                                    <del class="price-old">${{p.price}}</del>
                                                {% endif %}
                                                <span class="price-new">${{p.discount_price}}</span>
                                            </div> <!-- price-wrap.// -->
                                        </div>
                                      {% if request.user.type == 'customer' and not request.user.is_staff and p.stock > 0 %}
                                      <div class="col-6 col-md-12 col-lg-6 col-xl-6">
                                        <form method="POST" action="{% url 'products:add_to_cart' p.slug %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="quantity" value="1">
                                            <input type="hidden" name="id" value="{{ p.pk }}">
                                            <button class="btn btn-outline-danger float-right" type="submit">
                                                {% trans "Add to cart" %}
                                            </button>
                                        </form>
                                      </div>
                                      {% endif %}
                                    </div>
                                </div> <!-- action-wrap -->
                            </figcaption>
                        </figure> <!-- card // -->
                    </div> <!-- col // -->
                    {% endif %}
                {% endfor %}
            </div> <!-- row.// -->
        {% endfor %}
    </div> <!-- container .//  -->
</section>

{% endblock content %}