src/apps/product/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('distributor/<username>', ProductDistributorListView.as_view(), name='distributor'),
    path('category/<slug>', ProductCategoryListView.as_view(), name='category'),
    path('delete/request', ProductDeleteRequest.as_view(), name="delete_request"),
    path('delete/pending', ProductDeletePendingListView.as_view(), name='delete_pending'),
    path('approve/pending', ProductApprovePendingListView.as_view(), name='approve_pending'),
    path('create', ProductCreateView.as_view(), name="create"),
    path('search', ProductFilterView.as_view(), name='search'),
    path('featured', ProductFeaturedView.as_view(), name='featured'),
    path('<slug>', ProductDetailView.as_view(), name='detail'),
    path('<slug>/add', ProductAddToCartView.as_view(), name='add_to_cart'),
    path('<slug>/remove', ProductRemoveFromCartView.as_view(), name='remove_from_cart'),
    path('<slug>/rate', ProductRateView.as_view(), name='rate'),
    path('<slug>/edit', ProductUpdateView.as_view(), name='update'),
    path('<slug>/delete/', ProductDeleteView.as_view(), name="delete"),
    path('<slug>/approve/', ProductApproveView.as_view(), name='approve'),
    path('<slug>/reject/', ProductRejectView.as_view(), name='reject'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('products/', include('product.urls')),
    path('address/', include('address.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/product/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Product, ProductImage


class ProductForm(forms.ModelForm):
    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        required=False
    )

    field_order = [
        'name',
        'category',
        'description',
        'price',
        'discount',
        'stock',
        'images',
    ]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': _('Name'),
        })
        self.fields['category'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': _('Description'),
        })
        self.fields['price'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': _('Price'),
        })
        self.fields['discount'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': _('Discount'),
        })
        self.fields['stock'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': _('Stock'),
        })

    class Meta:
        model = Product
        fields = [
            'category',
            'name',
            'description',
            'price',
            'discount',
            'stock',
            'images'
        ]

    def clean_price(self):
        price = self.cleaned_data["price"]
        if price <= 0:
            raise forms.ValidationError('Price must be higher than 0.')
        return price

    def clean_stock(self):
        stock = self.cleaned_data["stock"]
        if stock <= 0:
            raise forms.ValidationError('Stock must be higher than 0.')
        return stock

    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)
        if commit:
            instance.is_approved = False
            instance.save()
        return instance

src/apps/product/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, Http404
from django.core.exceptions import ValidationError
from .models import Product, ProductLike, ProductImage
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from .forms import ProductForm
from django.views.generic import (
    View,
    DetailView,
    UpdateView,
    ListView,
    CreateView,
)
from django.utils.translation import gettext_lazy as _
from cart.models import CartItem
from decimal import Decimal
from django.db.models import Q


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        instance = context['product']
        category = instance.category.all().first()
        products = Product.objects.exclude(pk=instance.pk).by_order_amount(250, category=category).accepted()
        context['best_products'] = products
        return context


def _handle_product_form(request, product, images=None):
    if images is not None and len(images) > 4:
        raise ValidationError(_('Please select maximum 4 images for the product.'))

    queryset = ProductImage.objects.all().filter(product=product)
    if queryset.exists():
        for obj in queryset:
            obj.delete()

    for i in images:
        instance = ProductImage.objects.create(product=product, image=i)
        instance.save()


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_form.html'

    def get_success_url(self):
        return reverse_lazy('home')

    def form_valid(self, form):
        valid = super(ProductCreateView, self).form_valid(form)
        images = self.request.FILES.getlist("images")

        if valid:
            _handle_product_form(self.request, form.instance, images=images)
            instance = form.save(commit=False)
            instance.distributor = self.request.user
            if self.request.user.is_staff:
                instance.is_approved = True
            instance.save()
            return valid


class ProductApprovePendingListView(LoginRequiredMixin, ListView):
    queryset = Product.objects.all().pending()
    paginate_by = 10
    context_object_name = 'products'
    template_name = 'product_pending_approve.html'

    def get_context_data(self, *args, **kwargs):
        if self.request.user.is_staff:
            return super(ProductApprovePendingListView, self).get_context_data(**kwargs)
        else:
            raise Http404


class ProductApproveView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            info_message = _('You are not allowed for this action. Please sign in as ADMIN.')
        else:
            slug = self.kwargs.get("slug")
            instance = get_object_or_404(Product, slug=slug)
            instance.is_approved = True
            instance.save()
            info_message = _('Product has been approved successfully.')

        messages.add_message(request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductRejectView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            info_message = _('Product has been approved successfully.')
        else:
            slug = self.kwargs.get("slug")
            instance = get_object_or_404(Product, slug=slug)
            instance.is_active = False
            instance.save()
            info_message = _('Product has been rejected successfully.')

        messages.add_message(request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = "product_form.html"
    form_class = ProductForm

    def get_object(self):
        user = self.request.user
        slug = self.kwargs.get("slug")
        instance = get_object_or_404(Product, slug=slug)
        if user.type == 'distributor':
            if instance.is_active and not instance.is_deleted:
                return instance
            else:
                raise Http404
        elif user.is_staff:
            return instance
        else:
            raise Http404

    def form_valid(self, form):
        valid = super(ProductUpdateView, self).form_valid(form)
        images = self.request.FILES.getlist("images")
        if valid and images:
            _handle_product_form(self.request, form.instance, images=images)
        return valid


class ProductDeleteView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            info_message = _('You are not allowed for this action. Please sign in as ADMIN.')
        else:
            slug = self.kwargs.get("slug")
            instance = get_object_or_404(Product, slug=slug)
            instance.is_active = False
            instance.save()
            info_message = _('Product has been deleted successfully.')

        messages.add_message(request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductDeleteRequest(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        pk = self.request.POST.get("id")
        instance = get_object_or_404(Product, pk=pk)
        instance.is_deleted = True
        instance.save()
        info_message = _('Your delete request has been sent. We will inform you as soon as possible.')
        messages.add_message(self.request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductDeletePendingListView(LoginRequiredMixin, ListView):
    queryset = Product.objects.all().deleted()
    paginate_by = 10
    context_object_name = 'products'
    template_name = 'product_pending_delete.html'

    def get_context_data(self, *args, **kwargs):
        if self.request.user.is_staff:
            return super(ProductDeletePendingListView, self).get_context_data(**kwargs)
        else:
            raise Http404


class ProductAddToCartView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.type == 'customer':
            info_message = _('You need to sign in as a CUSTOMER to add items in your basket.')
            messages.add_message(self.request, messages.INFO, info_message)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        pk = request.POST.get("id")
        qty = int(request.POST.get("quantity"))
        product = get_object_or_404(Product, pk=pk)

        if product.stock == 0:
            info_message = _('Product is out of stock.')
            messages.add_message(self.request, messages.INFO, info_message)
        else:
            if product is not None and qty <= product.stock:
                cart = request.user.shopping_cart
                cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product, is_active=True)
                if created:
                    cart_item.quantity = qty
                    cart_item.is_active = True
                    cart_item.save()
                    info_message = _('Product is added to your basket.')
                else:
                    new_qty = cart_item.quantity + qty
                    if new_qty > product.stock:
                        info_message = _('Stock is not enough for quantity amount.')
                    else:
                        cart_item.quantity = new_qty
                        cart_item.save()
                        info_message = _('Quantity amount is updated.')
            else:
                info_message = _('Stock is not enough for quantity amount.')
            messages.add_message(self.request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductRemoveFromCartView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.type == 'customer':
            info_message = _('You need to sign in as a CUSTOMER to remove items from your basket')
            messages.add_message(self.request, messages.INFO, info_message)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        pk = request.POST.get("id")
        product = get_object_or_404(Product, pk=pk)
        cart = request.user.shopping_cart
        cart_item = get_object_or_404(CartItem, product=product, cart=cart, is_active=True)
        cart_item.delete()

        info_message = _('Product is removed from your basket.')
        messages.add_message(self.request, messages.INFO, info_message)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ProductRateView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        if not request.user.type == 'customer':
            info_message = _('You need to sign in as a CUSTOMER to rate products')
            messages.add_message(self.request, messages.INFO, info_message)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        pk = request.POST.get("id")
        rate = Decimal(request.POST.get("rating"))
        product = get_object_or_404(Product, pk=pk)
        product_like, created = ProductLike.objects.get_or_create(user=request.user, product=product)

        if rate > 10:
            rate = 10

        product_like.rate = rate
        product_like.save()

        info_message = _('Thank you for your vote.')
        messages.add_message(self.request, messages.INFO, info_message)

src/apps/product/templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}{{ product.name }}{% endblock title %}
{% block content %}
<section class="section-content bg padding-y-sm">
	<div class="container">
		<nav class="mb-4 mt-2">
			<ol class="breadcrumb">
			    <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
                {% if product.category.slug %}
                    <li class="breadcrumb-item"><a href="{% url 'products:category' product.category.first.slug %}">{{ product.category.first.name }}</a></li>
                {% endif %}
			    <li class="breadcrumb-item active" aria-current="page">{{ product.name|truncatechars:75 }}</li>
			</ol>
		</nav>
		<div class="row">
			<div class="col-12 mb-3">
				<main class="card">
					<div class="row no-gutters">
						<aside class="col-md-6 border-right my-auto">
							<article class="gallery-wrap">
								<div class="img-big-wrap">
									<div>
										<a href="{{ product.get_first_image_url }}" data-fancybox="images">
											<img src="{{ product.get_first_image_url }}"
													class="img-lg img-thumbnail" alt="{{ product.name }}"
													style="border: 0 none;">
										</a>
									</div>
								</div> <!-- slider-product.// -->
								<div class="img-small-wrap mt-5">
									{% for product_image in product.product_image.all  %}
										{% if forloop.counter > 1 %}
										<div class="item-gallery">
											<figure class="media">
												<a href="{{ product_image.image.url }}" data-fancybox="images">
													<img src="{{ product_image.image.url }}" class="img-sm img-thumbnail"
															alt="{{ product.name }}" style="border: 0 none;">
												</a>
											</figure>
										</div>
										{% endif %}
									{% endfor %}
								</div> <!-- slider-nav.// -->
							</article> <!-- gallery-wrap .end// -->
						</aside>
						<aside class="col-md-6">
							<article class="card-body">
								<!-- short-info-wrap -->
								<h3 class="title mb-3">{{ product.name }}</h3>
									<div class="mb-3">
										<var class="price h3 text-warning">
											{% if product.discount > 0 %}
												<del class="text-muted"><span class="num">${{ product.price }}</span></del>
												<br>
												<span class="num">${{ product.discount_price }}</span>
											{% else %}
												<span class="currency"></span><span class="num">${{ product.discount_price }}</span>
											{% endif %}
										</var>
										<br>
										{% if product.discount > 0 %}
											<var class="price">
												<span class="num text-danger">
													{% trans "Your Save" %} ${{ product.get_saved_price }}
												</span>
												<br>
											</var>
										{% endif %}
										<span class="num text-success">{% trans "Free shipping" %}</span>
									</div> <!-- price-detail-wrap .// -->
									<dl>
					  				<dt>{% trans "Description" %}</dt>
									  <dd><p class="mt-2" style="line-height: 1.8">{{ product.description }}</p></dd>
									</dl>
                                    {% if product.distributor %}
                                        <p class="text-muted">{% trans 'Ürün Sahibi:' %} <a href="{% url 'products:distributor' product.distributor.username %}">{{ product.distributor.username }}</a></p>
                                    {% endif %}
									<div class="rating-wrap">
										<div class="label-rating">
											<div class="row">
												<div class="col-4 my-auto text-warning">
													<i class="fas fa-star fa-2x"></i>
												</div>
												<div class="col-8 mt-2 pl-0">
													<span style="font-size: 1.3em;"><strong>{{ product.get_avg_like }}</strong></span><span class="text-muted" style="font-size: .9em;">/10</span>
													<p style="font-size: .9em;">{{ product.product_like.all.count}} {% trans "people rate this." %}</p>
												</div>
											</div>
										</div>
										<div class="label-rating">
											<div class="row">
												<div class="col my-2">
													<span style="font-size: 1.1em;">{{ product.order_amount }} {% trans "orders" %}</span>
												</div>
											</div>
										</div>
										{% if request.user.type == 'customer' and not request.user.is_staff %}
											<div class="label-rating">
												<form action="{% url 'products:rate' product.slug %}" method="POST">
													<div class="row">
														<div class="col-6 my-auto text-warning">
																{% csrf_token %}
																<input type="number" name="rating" id="ratingInput"
																		min="0" step="0.1" max="10"
																		class="form-control my-2" value="0" style="width: 65px;">
														</div>
														<div class="col-6 pl-0 my-auto">
															<button class="btn btn-outline-warning"
																			type="submit" name="id" value="{{ product.pk }}">
																{% trans "Rate this" %}
															</button>
														</div>
													</div>
												</form>
											</div>
										{% endif %}
									</div> <!-- rating-wrap.// -->
									{% if request.user.type == 'customer' and not request.user.is_staff %}
									<hr>
									<form method="POST" action="{% url 'products:add_to_cart' product.slug %}">
										<div class="row">
												{% csrf_token %}
												<input type="hidden" name="id" value="{{ product.pk }}">
												<div class="col-sm-6">
													<dl class="dlist-inline">
														{% if product.stock == 0 %}
																<dt>
																	<span class="badge bg-danger text-white"
																		style="height: 25px; line-height: 20px;">
																		{% trans "NO STOCK" %}
																	</span>
																</dt>
														{% else %}
																<dt>{% trans "Quantity" %}: </dt>
																<dd>
																	<input type="number" name="quantity" id="{{ product.pk }}"
																			min="1" step="1" max="{{ product.stock }}"
																			class="form-control my-2" value="1">
																</dd>
														{% endif %}
													</dl>  <!-- item-property .// -->
												</div> <!-- col.// -->
												{% if product.stock > 0 %}
													<div class="col-sm-6">
														<button type="submit" class="btn btn-outline-danger my-2 float-right">
															{% trans "Add to cart" %}
														</button>
													</div>
												{% endif %}
										</div>
									</form>
								{% endif %}
								</article> <!-- card-body.// -->
						</aside> <!-- col.// -->
					</div> <!-- row.// -->
				</main> <!-- card.// -->
			</div> <!-- col // -->
		</div> <!-- row.// -->
        {% if best_products %}
		<div class="row">
			<div class="col">
				<article class="card mt-3">
					<div class="card-body">
						<h5 class="text-center">{% trans "Top sellers products in" %} {{ product.category.first.name }}</h5>
						<table class="table shopping-cart-wrap">
							<thead class="text-muted">
								<tr>
									<th scope="col" width="10%"></th>
									<th scope="col" width="60%"></th>
									<th scope="col" width="15%"></th>
									<th scope="col" width="15%"></th>
								</tr>
							</thead>
							<tbody>
								{% for product in best_products %}
								<tr>
									<td>
										<figure class="media">
											<div class="img-wrap">
												<img src="{{ product.get_first_image_url }}" alt="{{ product.name }}"
														class="img-thumbnail img-sm">
											</div>
										</figure>
									</td>
									<td>
										<a href="{{ product.get_absolute_url }}">
											<h6 class="title">
												{{ product.name }}
											</h6>
										</a>
									</td>
									<td>
										<div class="price-wrap mt-2">
											<var class="price text-dark">
											{% if p.discount > 0 %}
											    <del class="price-old">${{product.price}}</del>
											{% endif %}
											<span class="price-new">${{product.discount_price}}</span>
											</var>
										</div> <!-- price-wrap .// -->
									</td>
									<td class="text-right">
										{% if request.user.type == 'customer' and not request.user.is_staff %}
										<form action="{% url 'products:add_to_cart' product.slug %}" method="post">
											{% csrf_token %}
											<input type="hidden" name="id" value="{{ product.pk }}">
											<input type="hidden" name="quantity" value="1">
											<button type="submit" name="button"
												class="btn btn-outline-danger mr-3 mt-2">
												{% trans "Add to cart" %}
											</button>
										</form>
										{% endif %}
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div> <!-- card-body.// -->
				</article> <!-- card.// -->
			</div>
		</div>
        {% endif %}
	</div><!-- container // -->
</section>
{% endblock content %}

{% block script %}
<script type="text/javascript">
		$(':input').on('keyup change click', function() {
			let value = parseInt($(this).val());
			if (value) {
				if (value < 0 || $(this).val().startsWith(0)) {
					$(this).val(1);
				}

				let max = parseInt($(this).attr("max"));
				if (value > max) {
					$(this).val(max);
				}
			}
		});
</script>
{% endblock script %}

src/apps/product/templates/product_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% if object.name %}{{ object.name }} | {% endif %}{% trans "Product" %}{% endblock title %}
{% block content %}
<div class="container">
  <nav class="mb-4 mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
        {% if object %}
          <li class="breadcrumb-item"><a href="{{ request.user.get_absolute_url }}">{% trans "My Profile" %}</a></li>
          <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object.name|truncatechars:30 }}</a></li>
        {% endif %}
        <li class="breadcrumb-item active" aria-current="page">
          {% if object %}
              {% trans "Edit" %}
          {% else %}
              {% trans "Register Product" %}
          {% endif %}
        </li>
    </ol>
  </nav>
  <div class="row">
    <div class="col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4 mt-2">
      <div class="card">
        <article class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.visible_fields %}
                {% csrf_token %}
                {% for field in form.visible_fields %}
                <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                  <div class="input-group">
                    {{ field }}
                  </div>
                </div>
                <p class="text-danger">
                  {% for error in field.errors %}
                      {{ error|escape }}
                  {% endfor %}
                </p>
                {% endfor %}
            {% endif %}
            <p class="text-danger">
              {% for non_field_error in form.non_field_errors  %}
                {{ non_field_error|striptags|escape }}
              {% endfor %}
              {% for hidden_field in form.hidden_fields %}
                {% for error in hidden_field.errors %}
                    {{ error|striptags|escape }}
                {% endfor %}
              {% endfor %}
            </p>
            <div class="form-group text-center">
              <button type="submit" class="btn btn-danger btn-block"> {% trans "Submit" %}  </button>
            </div>
          </form>
        </article>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/apps/product/templates/product_pending_approve.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ products.all.count }} | {% trans "waiting for approvement" %}{% endblock title %}
{% block content %}
<section class="section-content bg padding-y border-top">
	<div class="container">
		<nav class="mb-4 mt-3">
			<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
					<li class="breadcrumb-item active" aria-current="page">{% trans "Approvement pending products" %}</li>
			</ol>
		</nav>
		<div class="row">
				<main class="col-sm-12 mb-4">
					{% if products.all.count > 0 %}
					<div class="card">
						<table class="table shopping-cart-wrap">
							<thead class="text-muted">
								<tr>
									<th scope="col" width="20%">{% trans "Product" %}</th>
									<th scope="col" width="20%">{% trans "Name" %}</th>
									<th scope="col" width="15%">{% trans "Stock" %}</th>
									<th scope="col" width="10%">{% trans "Price" %}</th>
									<th scope="col" width="10%">{% trans "" %}</th>
								</tr>
							</thead>
							<tbody>
								{% for product in products %}
								<tr>
									<td class="align-middle">
										<figure class="media">
											<div class="img-wrap">
												<img src="{{ product.get_first_image_url }}" alt="{{ product.name }}"
														class="img-thumbnail img-sm">
											</div>
										</figure>
									</td>
									<td class="align-middle">
										<h6 class="title">
											<a href="{{ product.get_absolute_url }}">
												{{ product.name }}
											</a>
										</h6>
									</td>
									<td class="align-middle">
										<p>{{ product.stock }}</p>
									</td>
									<td class="align-middle">
										<p>${{ product.price }}</p>
									</td>
									<td>
										<div class="row">
											<div class="col-6">
												<form action="{% url 'products:approve' product.slug %}" method="post">
													{% csrf_token %}
													<button type="submit" name="button"
														class="btn btn-outline-success my-4">
														<i class="fas fa-check"></i>
													</button>
												</form>
											</div>
											<div class="col-6 pl-0">
												<form action="{% url 'products:reject' product.slug %}" method="post">
													{% csrf_token %}
													<button type="submit" name="button" class="btn btn-outline-danger my-4">
														<i class="fas fa-minus"></i>
													</button>
												</form>
											</div>
										</div>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div> <!-- card.// -->
					{% else %}
					<h5 class="text-center">
						{% trans "There are currently no registered products." %}
					</h5>
					{% endif %}

					{% if is_paginated %}
					<nav aria-label="Page navigation" class="mt-3">
						<ul class="pagination justify-content-end">
							{% if page_obj.has_previous %}
								<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
										<span aria-hidden="true">&laquo;</span>
										<span class="sr-only">Previous</span>
									</a>
								</li>
							{% else %}
								<li class="page-item disabled">
									<a href="javascript:void(0)" class="page-link">
										<span>&laquo;</span>
									</a>
								</li>
							{% endif %}
							{% for i in paginator.page_range %}
								{% if page_obj.number == i %}
									<li class="page-item active">
										<a class="page-link" href="?page={{ i }}">
											<span aria-hidden="true">{{ i }}</span>
											<span class="sr-only">(current)</span>
										</a>
									</li>
								{% else %}
									<li class="page-item">
										<a class="page-link" href="?page={{ i }}">{{ i }}</a>
									</li>
								{% endif %}
							{% endfor %}
							{% if page_obj.has_next %}
								<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.next_page_number }}">
										<span aria-hidden="true">&raquo;</span>
										<span class="sr-only">Next</span>
									</a>
								</li>
							{% else %}
								<li class="page-item disabled">
									<a href="javascript:void(0)" class="page-link">
										<span>&raquo;</span>
									</a>
								</li>
							{% endif %}
						</ul>
					</nav>
					{% endif %}
				</main> <!-- col.// -->
      </div>
    </div>
</section>
{% endblock content %}